baseURL = ""
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Ace documentation"
theme = "ace documentation"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = false
googleAnalytics = ""
themesDir = "themes"
publishDir = "public"

[params]
ordersectionsby = "weight"
disableSearch = false
disableReadmoreNav = false
highlightClientSide = false
menushortcutsnewtab = true

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.shortcuts]]
name = "More from us"
url = "https://vantage-design.com"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/vantagedesign/ace-documentation"
weight = 2

[[menu.shortcuts]]
name = "<button class='btn btn-success mt-n1'>Download</button>"
url = "https://github.com/vantagedesign/ace-documentation/releases"
weight = 3
